### ISSUE TITLE
Lambda → ECS Fargate への移行計画

### ISSUE THREAD

**Issue by kawafuchieirin** [kawafuchieirin/appraisal-app#9]
@claude
🎯 目的
Lambda で構築された FastAPI / Django アプリケーションを ECS Fargate に移行し、安定したデプロイと柔軟な開発環境を実現する。

✅ フェーズ1：準備
 AWS CLI, ECS CLI, Docker のローカル環境にインストール

```
brew install awscli
brew install ecs-cli
 AWS CLI 認証設定（aws configure）
```
AWSアカウントのアクセスキー、リージョン（例：ap-northeast-1）を設定

 ECS クラスターの作成

```
ecs-cli configure --cluster satei-app-cluster --default-launch-type FARGATE --region ap-northeast-1
ecs-cli up
 Dockerイメージの準備

--platform linux/amd64 でビルド済みの FastAPI / Django イメージを用意
```
ECR にそれぞれプッシュ

```
docker tag <local-image> <aws_account_id>.dkr.ecr.ap-northeast-1.amazonaws.com/<repo-name>
docker push ...
```
🧱 フェーズ2：構成ファイルの用意
 docker-compose.yml（アプリケーション構成）

例：

```
version: "3.8"
services:
  django:
    image: <ECR Django イメージURL>
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - ...
  fastapi:
    image: <ECR FastAPI イメージURL>
    ports:
      - "8001:8001"
    environment:
      - ...
 ecs-params.yml（Fargate設定）
```
```
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  network_mode: awsvpc
  requires_compatibilities:
    - FARGATE
  cpu: 512
  memory: 1024
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-xxxxxxxx
      security_groups:
        - sg-xxxxxxxx
      assign_public_ip: ENABLED
🚀 フェーズ3：デプロイ
 ECS クラスターにデプロイ
```

```
ecs-cli compose --file docker-compose.yml --project-name satei-app service up \
  --create-log-groups \
  --cluster-config satei-app-cluster
 サービスの稼働確認
```
```
ecs-cli compose --project-name satei-app service ps
```
🌐 フェーズ4：公開 & オートスケーリング
 ALB（Application Load Balancer）設定

ターゲットグループを2つ作成（FastAPI、Django）

リスナーで /api/*, /admin/* をルーティング

 Route 53 ドメイン設定（任意）

api.example.com, admin.example.com でDNSを設定

 ACM 証明書 + HTTPS対応

 オートスケーリング設定

タスク数のスケーリングを設定（例：CPU 80%超過で+1）

📦 フェーズ5：移行後確認
 /health /predict /admin/ などにアクセスして動作確認

 CloudWatch Logs にてログ出力の確認

 環境変数が反映されているか確認
